name: 🐛 Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug 🐛"]
body:
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true
  - type: dropdown
    id: versions
    attributes:
      label: Which browser are you using to access Simple Weather?
      description: If this issue is occurring on more than 1 version of the app, select the appropriate versions.
      multiple: true
      options:
       - Safari
       - Chrome
       - FireFox
       - Edge
       - Other (Please say in body)
    validations:
      required: true
